config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"
  
  resources :articles do
    resources :comments
    collection do
      delete :bulk_destroy
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  has_many :comments, dependent: :destroy

  enum :status, [ :public, :archived, :private], suffix: true

  def public_count
    where(status: 'public').count
  end

  validates :title, :body, presence: true
  validates :body, length: { minimum: 10 }
end
  

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  enum :status, [ :public, :archived, :private], suffix: true
end

app/models/concerns/visible.rb
module Visible
    extend ActiveSupport::Concern

    class_methods do
        def public_count
          where(status: 'public').count
        end
    end
  
    def archived?
        status == 'archived'
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
    #before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "kmbtjs", password: "secretpass", except: [:index, :show]


  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])  
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  def bulk_destroy
    Article.where(id: params[:collection_ids]).destroy_all
    redirect_to articles_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :status)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    http_basic_authenticate_with name: "kmbtjs", password: "secretpass", only: :destroy

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article), status: 303
    end

    private
        def comment_params
            params.require(:comment).permit(:commenter, :body, :status)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<div class="text-gray-800 ml-2 mt-12 flex flex-row">
  <%= form_with model: article do |form| %>
      <div class="p-3">
        <%= form.label :title %><br>
        <%= form.text_field :title %>
        <% article.errors.full_messages_for(:title).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    
      <div class="p-3">
        <%= form.label :body %><br>
        <%= form.text_area :body %><br>
        <% article.errors.full_messages_for(:body).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

      <div class="p-3">
        <%= form.label :status %>
        <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
      </div><br>

    <div class="flex flex-row">
      <button class="">
        <%= form.button "Create Article", type: :submit, class: :"bg-gray-500 hover:bg-gray-600 
        focus:outline-none focus:ring focus:ring-gray-300 
        rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3"%>
      </button>
    <% end %><br>
      <button class="bg-gray-500 hover:bg-gray-600 
      focus:outline-none focus:ring focus:ring-gray-300 
      rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3">
      <%= link_to "Back to Articles", articles_path %>
      </button>
    </div>
</div>
  

app/views/articles/edit.html.erb
<header>
    <div class="text-3xl font-bold mt-2 ml-12 absolute">Edit Article</div>
</header>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<header class="absolute text-3xl font-bold mt-3 ml-8">Articles</header>
<div class="relative pt-14 pl-4 flex-col">
    Article Count: <%= Article.public_count %>
        <div class="my-2">
        <%= form_with url: bulk_destroy_articles_path, method: :delete do |form| %>
            <ul>
            Article Title
                <% @articles.each do |article| %>
                    <% unless article.archived? %>
                        <li>
                        <input class="form-check-input appearance-none h-4 w-4 border border-gray-300 rounded-sm 
                                      bg-white checked:bg-blue-600 checked:border-blue-600 
                                      focus:outline-none transition duration-200 my-1 align-top 
                                      bg-no-repeat bg-center bg-contain float-left cursor-pointer mr-2" 
                                      type="checkbox" value="<%= article.id %>" id="checkbox1" name="collection_ids[]" />
                                      <%= link_to article.title, article %>
                        </li>
                    <% end %>
                <% end %>
            </ul>
        </div>
        
        <div class="flex flex-row">
        <div><%= form.button "Delete Articles", type: :submit, class: :"bg-gray-500 hover:bg-gray-600 
                                focus-outline-none focus:ring focus:ring-gray-300 
                                rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3" %></div>
        <% end %>
        <div>
        <button class="bg-gray-500 hover:bg-gray-600 
        focus:outline-none focus:ring focus:ring-gray-300 
        rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3">
    <%= link_to "Add New Article", new_article_path %></button></div>
        </div>
</div>

app/views/articles/new.html.erb
<header>
    <div class="text-3xl font-bold mt-3 ml-12 absolute">New Article</div>
</header>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="flex flex-col">
<section>
        <div class="p-3">
        <div class="mb-2"> Article Title:
            <%= @article.title %>
        </div>
        <div class="mb-3"> Article Body:
            <%= @article.body %></p>
        </div>
        </div>
        <div class="flex flex-row">
            <button class="bg-gray-500 hover:bg-gray-600 
                        focus:outline-none focus:ring focus:ring-gray-300 
                        rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3">
                        <%= link_to "Edit Article", edit_article_path(@article) %></button>
            <button class="bg-gray-500 hover:bg-gray-600 
                        focus:outline-none focus:ring focus:ring-gray-300 
                        rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3">
                        <%= link_to "Delete Article", article_path(@article), data: {
                                                turbo_method: :delete,
                                                turbo_confirm: "Are you Sure?"} %></button>

            <button class="bg-gray-500 hover:bg-gray-600 
                        focus:outline-none focus:ring focus:ring-gray-300 
                        rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3">
                        <%= link_to "Back to Articles", articles_path %></button>
        </div>
</section>

<section>
<div class="pt-3 ml-3">
    <div class="text-3xl font-bold pt-3 ml-3">Comments</div>
    <div class=""><%= render @article.comments %></div>
</div>
<div class="flex flex-col">
    <%= render 'comments/form' %>
</div>
</section>
</div>

app/views/comments/_comment.html.erb
<div class="">
  <% unless comment.archived? %>
    <div class="">
      Commenter: <%= comment.commenter %>
    </div>

    <div class="mb-3">
      Comment: <%= comment.body %>
    </div>
    </div>
<button class="bg-gray-500 hover:bg-gray-600 
              focus:outline-none focus:ring focus:ring-gray-300 
              rounded-full text-m text-gray-100 ml-1.5 p-2.5 px-3">
<%= link_to "Delete Comment", [comment.article, comment], data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>
<button>
  <% end %>

app/views/comments/_form.html.erb
<div class="relative text-gray-800 ml-3 mt-12 flex flex-col">
  <h2>Add a comment:</h2>
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <div class="p-3">
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </div>
  <div class="p-3">
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </div>
  <div class="p-3">
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>


  <div>
  <button class="">
    <%= form.button "Create Comment", type: :submit, class: :"bg-gray-500 hover:bg-gray-600 
    focus:outline-none focus:ring focus:ring-gray-300 
    rounded-full text-m text-gray-100 ml-2 p-2.5 px-0.5"%></button>
  <% end %>
</div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
      <%= yield %>
    </main>
  </body>
</html>